- client.go
- server.go
- server_test.go
This apples logic to correctly Close a server, as well as implements
graceful shutdown. This ensures that inflight requests are not
interrupted and works similar to the functionality in `net/http`.
This required a fair bit of refactoring around how the connection is
managed. The connection now has an explicit wrapper object, ensuring
that shutdown happens in a coordinated fashion, whether or not a
forceful close or graceful shutdown is called.
In addition to the above, hardening around the accept loop has been
added. We now correctly exit on non-temporary errors and debounce the
accept call when encountering repeated errors. This should address some
issues where `SIGTERM` was not honored when dropping into the accept
spin.
> ttrpc: implement Close and Shutdown

- client.go
- server.go
- server_test.go
The request and response requests opened up a nasty race condition where
waiters could find themselves either blocked or receiving errant errors.
The result was low performance and inadvertent busy waits. This
refactors the client to have a single request into the main client loop,
eliminating the race.
The reason for the original design was to allow a sender to control
request and response individually to make unit testing easier. The unit
test has now been refactored to use a channel to ensure that requests
are serviced on graceful shutdown.
> ttrpc: refactor client to better handle EOF

- config.go
- handshake.go
- server.go
- server_test.go
- unixcreds.go
Because ttrpc can be used with abstract sockets, it is critical to
ensure that only certain users can connect to the unix socket. This is
of particular interest in the primary use case of containerd, where a
shim may run as root and any user can connection.
With this, we get a few nice features. The first is the concept of a
`Handshaker` that allows one to intercept each connection and replace it
with one of their own. The enables credential checks and other measures,
such as tls. The second is that servers now support configuration. This
allows one to inject a handshaker for each connection. Other options
will be added in the future.
> ttrpc: implement unix socket credentials

- handshake.go
- server.go
- server_test.go
- unixcreds.go
Because of issues with glibc, using the `os/user` package can cause when
calling `user.Current()`. Neither the Go maintainers or glibc developers
could be bothered to fix it, so we have to work around it by calling the
uid and gid functions directly. This is probably better because we don't
actually use much of the data provided in the `user.User` struct.
This required some refactoring to have better control over when the uid
and gid are resolved. Rather than checking the current user on every
connection, we now resolve it once at initialization. To test that this
provided an improvement in performance, a benchmark was added.
Unfortunately, this exposed a regression in the performance of unix
sockets in Go when `(*UnixConn).File` is called. The underlying culprit
of this performance …
> ttrpc: use os.Getuid/os.Getgid directly

- unixcreds_linux.go
BSD does have LOCAL_PEERCRED but x/sys.unix does not yet have support for it.
I will add support and do a proper fix later.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>
> SO_PEERCRED is Linux only

- unixcreds_linux.go
~This commit also eliminates call for `os/user.Current()`,
which segfaults when glibc is statically linkedin.
(moby/moby#29478)~ (EDIT: the segfault issue is already handled in #13)
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
> unixcreds: use euid instead of uid

- client.go
- server.go
- server_test.go
To gracefully handle scenarios where the connection is closed or the
client is closed, we now set the final error to be `ErrClosed`. Callers
can resolve it through using `errors.Cause` to detect this condition.
Closes #16
> ttrpc: return ErrClosed when client is shutdown

- client.go
Because `shutdownErr` will likely be `nil` in the close select branch,
returning it to waiters will result in the waiting `(*Client).Call`
returning `(nil, nil)`. This should take whatever is set for the client
as the exit condition, which is likely to be `ErrClosed`.
> ttrpc: return correct error on (*Client).Close

- client.go
Where do you think the right place is to call the close func internally?  I think its best that we call this internally on an ErrClosed else we would have to handle the error all over the calling code.  
> Add onclose func

- client.go
- server.go
- server_test.go
- types.go
Adds a new field to the `Request` type which specifies a timeout (in
nanoseconds) for the request. This is propagated on method dispatch as a
context timeout.
There was some discussion here on supporting a broader "metadata" field
(similar to grpc) that can be used for other things, but we ended up
with a dedicated field because it is lighter weight and expect it to be
used pretty heavily as is.... metadata may be added in the future, but
is not necessary for timeouts.
Also discussed using a deadline vs a timeout in the request and decided
to go with a timeout in order to deal with potential clock skew between
the client and server. This also has the side-effect of eliminating the
protocol/wire overhead from the request timeout.
> Add support for request timeout propgation.

- client.go
Make `OnClose` an create option instead of a separate function.
`NewClient` starts a goroutine, which calls `closeFunc` before exit.
Setting `closeFunc` after `NewClient` separately introduces a race condition:
1) The race condition can cause unexpected behavior, e.g. the function is not fully copied before being invoked;
2) There is no way to guarantee a `closeFunc` is called given that the connection may be gone before `OnClose` is set.
Signed-off-by: Lantao Liu <lantaol@google.com>
> Make onclose an option.

- server.go
- server_test.go
Currently the EOF that the server gets when a client connection is
closed is being ignored, which means that the goroutine that is
processing the client connection will never exit. If it never exits
it will never close the underlying unix socket and this would lead
to a file descriptor leak.
Signed-off-by: Georgi Sabev <georgethebeatle@gmail.com>
Reprodction steps:
```
ctr image pull docker.io/library/alpine:latest
ctr run --rm docker.io/library/alpine:latest test sleep 9999
ls -la /proc/$(pidof containerd-shim)/fd | grep socket | wc -l
2
kill $(pidof containerd)
containerd & 
ls -la /proc/$(pidof containerd-shim)/fd | grep socket | wc -l
3
```
> Handle EOF to prevent file descriptor leak

- server.go
Return if client is gone, log all other errors
Co-authored-by: Giuseppe Capizzi <gcapizzi@pivotal.io>
Signed-off-by: Georgi Sabev <georgethebeatle@gmail.com>
This PR addresses a [comment](https://github.com/containerd/ttrpc/pull/37/files#r282957868) on #37 by @stevvooe
> Improve connection error handling

- client.go
- config.go
- example/cmd/main.go
- interceptor.go
- server.go
- services.go
> Add client and server unary interceptors

- client.go
- example/cmd/main.go
- metadata.go
- metadata_test.go
- server.go
- server_test.go
- types.go
> metadata as KeyValue type

- channel.go
- channel_test.go
- client.go
- server.go
- server_test.go
> Refactor close handling for ttrpc clients

- client.go
When call server.Close(), server will close all listener and notify
flighting-connection to shutdown. Connections are closed asynchronously.
In TestClientEOF, client can send request into closing-connection. But
the read for reply will return error if the closing-connection is
shutdown.
In this case, we should filter error for client side about `read:
connection reset by peer`.
Signed-off-by: Wei Fu <fuweid89@gmail.com>
> return ErrClosed if read: connection reset by peer

- .travis.yml
when enable go module, go get will update the required version. It is
not supported to run in CI.
More info: golang/go#27643.
Signed-off-by: Wei Fu <fuweid89@gmail.com>
> .travis: don't call go get if there is go.mod

- services.go
Since proto.Marshal() on nil will crash runtime, thus
it's should check 'resp' before marshaling on it. If it's
nil, return directly.
Signed-off-by: lifupan <lifupan@gmail.com>
> ttrpc: fix the issue of marshaling on nil will crash the server

- channel.go
- channel_test.go
- client.go
- codes/code_string.go
- codes/codes.go
- codes/codes_test.go
- codes/doc.go
- go.mod
- go.sum
- server.go
- server_test.go
- services.go
- status/doc.go
- status/status.go
- status/status_ext_test.go
- status/status_test.go
This copies the codes and status package from grpc as it is the only references
to the grpc project from ttrpc.  This will help ensure that API breaking changes
in grpc do not affect ttrpc.
> Copy codes and status pkg from grpc

- server.go
- server_test.go
When the connection closed, it should delete
the connection from server's connections map.
Signed-off-by: fupan.lfp <fupan.lfp@antfin.com>
> server: fix the issue if connections leak

- client.go
- client_test.go
- server_test.go
ttrpc provides WithOnClose option for user and ttrpc will call the
callback function when connection is closed unexpectedly or the ttrpc
client's Close() method is called. containerd runtime plugin uses it
to handle cleanup the resources created by containerd shim.
But the ttrpc client's Close() is only trigger and the shim's cleanup
resource callback is called asynchronously, which might make part of
resources leaky. There is an example from containerd-runtime-v2 for
runc:
```happy
[Task.Delete goroutine]         [cleanupCallback goroutine]
call ttrpc client.Close() -->
read bundle and call runc delete
delete bundle
```
If the cleanupCallback is called after deleting bundle, the callback
will fail to call runc delete. If there is any running processes, the
resource becomes leaky. …
> client: add UserOnCloseWait function

- .travis.yml
I saw https://github.com/containerd/ttrpc/issues/62 was reported to panic on Go 1.15, so adding that too travis. Kept Go 1.13 for now, as that's still used by containerd
> travis: add go 1.15

- .github/workflows/ci.yml
- README.md
This is mostly a copy of the workflow from the github.com/containerd/typeurl repository. After this we can remove travis.
> Use GitHub Actions for CI

- README.md
ttrpc is not new. It has been used by containerd for years.
Fixes #59.
> Remove "Very new" and checked TODO items

- server_test.go
- services.go
gRPC has UNIMPLEMENTED status code that indicates a requested method
is not implemented. However ttrpc was returning codes.NotFound which
could be returned when a request entity was not there.
This fix changes the status code from codes.NotFound to
codes.Unimplemented to disambiguate and be more compatible with gRPC.
> Return Unimplemented when services or methods are not implemented

- .github/workflows/ci.yml
- example/cmd/handshaker_linux.go
- example/cmd/handshaker_other.go
- example/cmd/main.go
- server_linux_test.go
- server_test.go
Abstract sockets, procfs and unix.Ucred are only available on Linux.
> Make "go test" and "go build" work on macOS

- client.go
Late last year I created #73 in an attempt to solve #72. This PR had some feedback that I never had a chance to properly address. I've now revisited this area and taken a different approach, which I think is better to put in a fresh PR, so that's what we have here.
Originally I had changed both the client and server code to prevent this deadlock on both ends. However, after thinking on this recently, I think the server code is alright as is. The core issue is that the client would block sending to the server, and the server would block sending back to the client, and thus neither would read from the other and we would deadlock. This is definitely undesirable behavior from the client, but on the server end I think it is reasonable to block reading from a client if it is not draining its …
> client: Handle sending/receiving in separate goroutines

- .github/workflows/ci.yml
- .golangci.yml
- client.go
- client_test.go
- example/cmd/handshaker_other.go
- handshake.go
- interceptor.go
- server_test.go
- types.go
- unixcreds_linux.go
Cleans up CI some and uses a similar approach to other repos
> Update CI project checks to use containerd project action

- unixcreds_linux.go
Wrap ucredErr which is set by unix.GetsockoptUcred, not the nil err.
> Wrap correct error on unix.GetsockoptUcred failure

- server_test.go
This test occasionally fails on Windows. This commit logs extra
information about the error to understand the situation better.
> Log the error's underyling errno if there is

- .gitattributes
Git by default uses CR+LF on Windows, whereas gofmt always
uses LF even on Windows.
This commit lets Git uses LF on Windows.
> Use CR+LF instead of LF regardless of OS

- .github/workflows/ci.yml
We have lost Codecov since #101. While the main containerd repository
doesn't have that, ttrpc could have Codecov without much complications.
> Enable Codecov again

- .github/workflows/ci.yml
> Update checkout and lint actions

- channel.go
- client.go
- errors.go
- server.go
- stream.go
And add a little documentation.
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
> *.go: organize errors to one spot

- .github/workflows/ci.yml
- README.md
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
From the slack conversation, it seems this codecov report is not useful and not quite accurate. It fails to reference git commits, and lists files that do not exist. I think getting a trusted local make target is a better focus.
> *: remove codecov

- Makefile
There is no Makefile target for `checkprotos` -- this is a typo of the `check-protos` target. This PR fixes those references.
Signed-off-by: Ethan Lowman <ethan.lowman@datadoghq.com>
> build: Fix references to check-protos target in Makefile

- server.go
In a connection, streams are added only, but not deleted.
When replying to the last data, delete the stream from map.
And delete operations require concurrency.
Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>
> stream: fix the map of streams leak

- server.go
The ttrpc server somtimes receives `ECONNRESET` rather than `EOF` when the client is exited. Such as reading from a closed connection. Handle it properly to avoid goroutine and connection leak.
Below is a debug example:
```
> github.com/containerd/ttrpc.(*serverConn).run() containerd/ttrpc/server.go:470 (hits goroutine(23900):1 total:3) (PC: 0x55f06b5a7cb3)
(dlv) p err
error(*errors.errorString) *{s: "EOF"}
(dlv) c
> github.com/containerd/ttrpc.(*serverConn).run() containerd/ttrpc/server.go:470 (hits goroutine(47938):1 total:4) (PC: 0x55f06b5a7cb3)
(dlv) p err
error(*net.OpError) *{
Op: "read",
Net: "unix",
Source: net.Addr(*net.UnixAddr) *{
Name: "/run/containerd/containerd.sock.ttrpc",
Net: "unix",},
Addr: net.Addr(*net.UnixAddr) *{Name: "@", Net: "unix"},
Err: error(*os.SyscallError) …
```
> server: Fix connection issues when receiving ECONNRESET

- server_test.go
TestServerShutdown is often failing on Windows. This change may help troubleshooting easier.
> Make checkServerShutdown verbose

- server.go
- server_test.go
Fixes #129 
Simplify close idle connections logic in server shutdown to be more
intuitive. Modify add connection logic to check if server has been
shutdown before adding any new connections. Modify test to make all
calls before server shutdown.
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
> Fix server shutdown logic

- server_test.go
Make `TestServerRequestTimeout` deadline assertion log print expected
and actual values in the same format for more clear troubleshooting.
For troubleshooting #131
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
> Rework deadline assertion logging to be more clear

- .github/workflows/ci.yml
- .golangci.yml
- Makefile
Update GitHub actions runner OS from Ubuntu 18.04 to Ubuntu 22.04.
Update Go compiler from Go 1.17 to Go 1.20. Update actions/setup-go from
v2 to v3. Update golangci-lint to v1.51.x for Go 1.20 support. Remove
deprecated `-i` flag from make coverage target.
Related issue: https://github.com/containerd/project/issues/95
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
> Update GitHub actions CI workflow

- server.go
Fixes #142 
Unwrap `io.EOF` and `io.ErrUnexpectedEOF` in server connection receive error handling. When read message errors occurs, the error is wrapped to be more distinguishable from read message header errors; however, without unwrapping the errors here the result would be leaked server connections for connections where the client is now gone.
Signed-of-by: Austin Vazquez <macedonv@amazon.com>
> Unwrap IO errors in server connection error handling

- client.go
- stream.go
Prevent panic from closing recv channel, which may be written to after close. Use a separate channel to signal recv has closed and check that channel on read and write.
Alternative to #139 for https://github.com/containerd/containerd/issues/8390
> Add recvClose channel to stream

- server_test.go
In the test for client `Call()` failing with `ErrClosed` on a closed server, wait for the client's `OnClose()` handler to get triggered to make sure closing the socket had properly been administered on the client's side. Otherwise trying a new `Call()` might fail with some other error than `ErrClosed`, for instance `ENOTCONN`.
This commit was split out from #145 as a PR of its own.
> server_test: wait for OnClose in TestClientEOF.

- client.go
While looking at `client.go:UserOnCloseWait()` based on a review comment for #150, I spotted something that looks like grammar errors in a docstring comment which then ends up being part of the package [documentation here](https://pkg.go.dev/github.com/containerd/ttrpc#Client.UserOnCloseWait).
Can some of the native speakers double-check that I didn't simply trade a grammar error for another one ?
> Fix grammar in comment for UserOnCloseWait.

- client.go
- config.go
- interceptor_test.go
Add `WithChainUnaryClientInterceptor` and `WithChainUnaryServerInterceptor` client and server options. These allow registering more than one client and server side interceptor which then get chained and invoked in the order of registration.
This should allow us to implement opentelemetry instrumentation for unary calls as unary interceptors while allowing users to keep intercepting their client and server side ttrpc calls for other reasons at the same time. These commits were split out from #145.
> Implement support for unary interceptor chaining.

- cmd/protoc-gen-go-ttrpc/main.go
Fixes error
```
is a proto3 file that contains optional fields, but code generator protoc-gen-go-ttrpc hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.
```
> Fix proto3 generation error

- .github/workflows/ci.yml
NodeJS 16 is EOL and GitHub Actions packages have been releases to run on NodeJS 20.
This change updates the GitHub Actions packages to resolve deprecation warnings
CI runs on PR
- https://nodejs.org/en/blog/announcements/nodejs16-eol
- https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Update GitHub Actions CI to resolve deprecation warnings

- client.go
- client_test.go
#137 
Closes the receiver goroutine without setting the client error when the client is closed. Client error will be set on next dispatch call invoked if any.
Adds unit test which calls test service call after client is closed. Before the change, the test failed 1 in every ~3000 runs. After the change, the test passed successfully 10000 runs in a row.
Run test:
```
go test -timeout 300s -tags unit,integration -run ^TestClientReturnsErrClosedAfterClose$ github.com/containerd/ttrpc -v -race -count=10000
```
Test failure without fix:
```
=== RUN   TestClientReturnsErrClosedAfterClose
client_test.go:100: Expected ErrClosed after connection has been closed, got context canceled
--- FAIL: TestClientReturnsErrClosedAfterClose (0.00s)
FAIL
FAIL    github.com/containerd/ttrpc     0.648s
FAIL
``` …
> [release/1.1] Fix context cancelled error after client close

- README.md
The current badge query shows CI is failing which should not be the case.
This change updates the build status badge to reflect CI workflow status.
> Fix CI build status badge in readme

- .github/workflows/ci.yml
- README.md
The release/1.1 branch currently has no CI for validating changes.
This change backports the following CI updates and enables CI for the branch.
- https://github.com/containerd/ttrpc/commit/9660e6b7a5fc1929620f5ebd29db756a4e992214 - remove codecov
- https://github.com/containerd/ttrpc/commit/c7b5a322eda63419e2dafa8dd215b08739ebe9f5 - update GitHub Actions CI workflow Note: drops unit testing on windows-latest due to test failure for unhandled edge case on Windows. Opened #164 
- https://github.com/containerd/ttrpc/commit/589a593abc38264094c47baf83bc69b2cff37524 - update GitHub Actions CI to resolve deprecation warnings
> [release/1.1] Backport CI updates and enable CI on release 1.1 branch

- channel.go
- channel_test.go
- errors.go
Reject oversized messages on the sender side (keeping the receiver side rejection code intact). Do not forcibly close in `channel.send()` the underlying connection when an oversized message is rejected.
This should provide minimal low-level means for ttrpc-based applications to detect oversized requests in `client.Call()` and attempt an application level recovery/corrective actions, if the high-level protocol is designed with this in mind.
> channel: reject oversized messages on the sender side(, too).

- server.go
- server_test.go
Fix a race where an asynchronous server.Serve() invoked in a a goroutine races with an almost immediate server.Shutdown().
If Shutdown() finishes its locked closing of listeners before Serve() gets around to add the new one, Serve will sit stuck forever in l.Accept(), unless the caller closes the listener in addition to Shutdown().
This is probably almost impossible to trigger in real life, but unit tests which run the server and client in the same process can trigger this. If a test then tries to verify after a Shutdown()  a final ErrServerClosed error from Serve() it gets stuck forever.
> server: fix a Serve() vs. (immediate) Shutdown() race

- metadata.go
- metadata_test.go
`MD` is not thread-safe so sometimes we need to make a copy before modification, e.g. in containerd, 
https://github.com/containerd/containerd/blob/c3efa0cb339ffc2d6c9f03d7fb4e5e6577d0194b/pkg/namespaces/ttrpc.go#L30-L36
This PR adds a `MD.Clone` function, similar to golang's `http.Header.Clone` (the code is copied there). Also add a benchmark that shows golang's implementation is better than a simple copy approach (both memory&latency):
```shell
$ go test -bench='Benchmark.*Clone' -benchmem
goos: linux
goarch: amd64
pkg: github.com/containerd/ttrpc
cpu: Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
BenchmarkMetadataClone/size=5-4          2663775               494.2 ns/op            80 B/op          1 allocs/op
BenchmarkMetadataClone/size=10-4          707372              1608 ns/op …
```
> Add MD.Clone function
